[default]
email_host = "localhost"
email_port = 25
email_from_address = "noreply@example.com"
web_address = "http://localhost:8000"
secret_key = "UZ/Q8SFljW9D7BQbTyIFWaYCZ4JOHczt7XMgdYXwJLk="
dates_per_day = 3
days_deadline = 1
impressum = ""

[default.databases.database]
url = "postgres://audition_dates:shouldbesecret@localhost/audition_dates"
